Attribute VB_Name = "MsSQLBlind"
' This code module rebuilt by VBRezQ v3.3a.  2-Feb-2012 / 19:56:24
Option Explicit 
 
'Sub Subr_687()
'N  * ref: __vbaExceptHandler
'N  * ref: Subr_185
'N  * ref: __vbaVarDup
'N  * ref: IIf(
'N  * ref: " "
'N  * ref: Subr_184
'N  * ref: __vbaVarCat
'N  * ref: " %True_Expression%"
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaStrCmp
'N  * ref: "("
'N  * ref: "1=1"
'N  * ref: "x"
'N  * ref: " and "
'N  * ref: "="
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeVarList
'End Sub
 
'Sub Subr_688()
'N  * ref: __vbaExceptHandler
'N  * ref: __vbaLenBstr
'N  * ref: "NULL"
'N  * ref: __vbaVarCopy
'N  * ref: __vbaVarForInit
'N  * ref: __vbaVarMove
'N  * ref: __vbaVarCat
'N  * ref: __vbaI4Var
'N  * ref: "char("
'N  * ref: Mid(
'N  * ref: __vbaStrVarVal
'N  * ref: Asc(
'N  * ref: ")%2b"
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarForNext
'N  * ref: __vbaLenVar
'N  * ref: __vbaVarSub
'N  * ref: Left(
'N  * ref: __vbaStrCat
'N  * ref: "'"
'N  * ref: __vbaStrMove
'N  * ref: "'"
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVar
'End Sub
 
'Sub Subr_689()
'N  * ref: __vbaExceptHandler
'N  * ref: __vbaVarDup
'N  * ref: __vbaVarVargNofree
'N  * ref: __vbaVarAdd
'N  * ref: __vbaVargVarMove
'N  * ref: __vbaVarSub
'N  * ref: __vbaVarTstGt
'N  * ref: __vbaVarDiv
'N  * ref: __vbaVarInt
'N  * ref: __vbaVarAdd
'N  * ref: __vbaVarMove
'N  * ref: __vbaI4Var
'N  * ref: Chr(
'N  * ref: ": "
'N  * ref: __vbaVarCat
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: "ascii(substring(("
'N  * ref: "),"
'N  * ref: ",1))<"
'N  * ref: __vbaStrVarVal
'N  * ref: "%True_Expression%"
'N  * ref: Replace(
'N  * ref: __vbaStrMove
'N  * ref: __vbaStrCopy
'N  * ref: Subr_151
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaInStr
'N  * ref: __vbaVarCopy
'N  * ref: Subr_689
'N  * ref: __vbaVarMove
'N  * ref: __vbaVarTstLe
'N  * ref: Subr_689
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeVar
'N  * ref: "?"
'N  * ref: Asc(
'N  * ref: __vbaVarMove
'N  * ref: __vbaVarMove
'N  * ref: __vbaI4Var
'N  * ref: Chr(
'N  * ref: ": "
'N  * ref: __vbaVarCat
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: "ascii(substring(("
'N  * ref: "),"
'N  * ref: ",1))="
'N  * ref: __vbaStrVarVal
'N  * ref: "%True_Expression%"
'N  * ref: Replace(
'N  * ref: __vbaStrMove
'N  * ref: __vbaStrCopy
'N  * ref: Subr_151
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaInStr
'N  * ref: __vbaVarCopy
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVar
'End Sub
 
'Sub Subr_690()
'N  * ref: __vbaExceptHandler
'N  * ref: __vbaVarVargNofree
'N  * ref: __vbaVarAdd
'N  * ref: __vbaVargVarMove
'N  * ref: __vbaOnError
'N  * ref: __vbaVarSub
'N  * ref: __vbaVarTstGt
'N  * ref: __vbaVarSub
'N  * ref: __vbaVarDiv
'N  * ref: __vbaVarInt
'N  * ref: __vbaVarAdd
'N  * ref: __vbaVarMove
'N  * ref: "Check if length of '"
'N  * ref: "' is <"
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: "))<"
'N  * ref: __vbaVarCat
'N  * ref: __vbaStrVarVal
'N  * ref: "%True_Expression%"
'N  * ref: Replace(
'N  * ref: __vbaStrMove
'N  * ref: __vbaStrCopy
'N  * ref: Subr_151
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaLenVar
'N  * ref: __vbaI4Var
'N  * ref: Mid(
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeVar
'N  * ref: __vbaInStr
'N  * ref: __vbaVargVarCopy
'N  * ref: Subr_690
'N  * ref: __vbaVargVarCopy
'N  * ref: Subr_690
'N  * ref: __vbaVarTstLe
'N  * ref: "Can not get Length of '"
'N  * ref: "'"
'N  * ref: __vbaVarCat
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarMove
'N  * ref: __vbaExitProc
'N  * ref: __vbaVarSub
'N  * ref: __vbaVargVarMove
'N  * ref: "Check if length of '"
'N  * ref: "' is ="
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: "Len(("
'N  * ref: "))="
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaStrVarVal
'N  * ref: "%True_Expression%"
'N  * ref: Replace(
'N  * ref: __vbaStrMove
'N  * ref: __vbaStrCopy
'N  * ref: Subr_151
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaLenVar
'N  * ref: __vbaI4Var
'N  * ref: Mid(
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeVar
'N  * ref: __vbaInStr
'N  * ref: "Length of '"
'N  * ref: "' is "
'N  * ref: __vbaVarCat
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarCopy
'N  * ref: Subr_690
'N  * ref: __vbaVarMove
'N  * ref: __vbaExitProc
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVar
'End Sub
 
'Sub Subr_691()
'N  * ref: __vbaExceptHandler
'N  * ref: __vbaOnError
'N  * ref: __vbaVarVargNofree
'N  * ref: __vbaVarTstNe
'N  * ref: __vbaStrVarCopy
'N  * ref: __vbaStrMove
'N  * ref: "Find length of '"
'N  * ref: "'"
'N  * ref: __vbaVarCat
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: Subr_690
'N  * ref: __vbaI2Var
'N  * ref: ": "
'N  * ref: __vbaVarVargNofree
'N  * ref: Subr_143
'N  * ref: __vbaLenBstr
'N  * ref: __vbaVarForInit
'N  * ref: ": "
'N  * ref: __vbaVarVargNofree
'N  * ref: Subr_143
'N  * ref: Subr_689
'N  * ref: __vbaI4Var
'N  * ref: Chr(
'N  * ref: __vbaStrVarMove
'N  * ref: __vbaStrMove
'N  * ref: __vbaVarForNext
'N  * ref: "[SKIPPED]"
'N  * ref: __vbaStrCat
'N  * ref: __vbaVarMove
'N  * ref: "Skipped!"
'N  * ref: __vbaVarDup
'N  * ref: Subr_143
'N  * ref: __vbaExitProc
'N  * ref: __vbaVarCopy
'N  * ref: "SKIPPED"
'N  * ref: __vbaStrCat
'N  * ref: __vbaVarMove
'N  * ref: __vbaExitProc
'N  * ref: __vbaExitProc
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStr
'N  * ref: __vbaErrorOverflow
'End Sub
 
'Sub Subr_692()
'N  * ref: __vbaExceptHandler
'N  * ref: "Keyword is not effective, if you are sure the target is vulnerable, Try again with a manual keyword"
'N  * ref: __vbaVarDup
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaStrCmp
'N  * ref: Subr_687
'N  * ref: __vbaStrVarMove
'N  * ref: __vbaStrMove
'N  * ref: __vbaFreeVar
'N  * ref: __vbaVarDup
'N  * ref: "Current DB"
'N  * ref: "db_name()"
'N  * ref: Subr_691
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarTstNe
'N  * ref: __vbaVarCat
'N  * ref: "Current DB: "
'N  * ref: Subr_143
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaNew2
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaStrCat
'N  * ref: "Current DB: "
'N  * ref: __vbaStrMove
'N  * ref: vbTab
'N  * ref: vbCrLf
'N  * ref: __vbaStrVarVal
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaStrVarCopy
'N  * ref: __vbaStrMove
'N  * ref: Subr_169
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarDup
'N  * ref: __vbaVarTstEq
'N  * ref: "Cannot get current db name!"
'N  * ref: Subr_143
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVar
'End Sub
 
'Sub Subr_693()
'N  * ref: __vbaExceptHandler
'N  * ref: __vbaVarMove
'N  * ref: __vbaVarDup
'N  * ref: __vbaVarCat
'N  * ref: "Data Base"
'N  * ref: "db_name("
'N  * ref: ")"
'N  * ref: Subr_691
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarTstNe
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaHresultCheckObj
'N  * ref: vbTab
'N  * ref: "Data Bases: "
'N  * ref: __vbaVarCmpEq
'N  * ref: __vbaVarMove
'N  * ref: IIf(
'N  * ref: vbTab
'N  * ref: vbCrLf
'N  * ref: __vbaStrVarVal
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVarList
'N  * ref: Subr_169
'N  * ref: __vbaFreeVar
'N  * ref: __vbaVarDup
'N  * ref: __vbaVarAdd
'N  * ref: __vbaVarMove
'N  * ref: __vbaVarTstEq
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVar
'End Sub
 
'Sub Subr_694()
'N  * ref: __vbaExceptHandler
'N  * ref: __vbaVarDup
'N  * ref: "Current User"
'N  * ref: "user"
'N  * ref: Subr_691
'N  * ref: __vbaStrVarMove
'N  * ref: __vbaStrMove
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaStrCmp
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaNew2
'N  * ref: __vbaHresultCheckObj
'N  * ref: "Current User: "
'N  * ref: __vbaStrCat
'N  * ref: vbTab
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrCat
'N  * ref: vbCrLf
'N  * ref: __vbaStrCat
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeObjList
'N  * ref: "Version"
'N  * ref: "@@version"
'N  * ref: Subr_691
'N  * ref: __vbaStrVarMove
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaStrCmp
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaNew2
'N  * ref: __vbaHresultCheckObj
'N  * ref: "Sql Version: "
'N  * ref: __vbaStrCat
'N  * ref: vbTab
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrCat
'N  * ref: vbCrLf
'N  * ref: __vbaStrCat
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeObjList
'N  * ref: "Current DB"
'N  * ref: "db_name()"
'N  * ref: Subr_691
'N  * ref: __vbaStrVarMove
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaStrCmp
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaNew2
'N  * ref: __vbaHresultCheckObj
'N  * ref: "Current DB: "
'N  * ref: __vbaStrCat
'N  * ref: vbTab
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrCat
'N  * ref: vbCrLf
'N  * ref: __vbaStrCat
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeObjList
'N  * ref: "System User"
'N  * ref: "system_user"
'N  * ref: Subr_691
'N  * ref: __vbaStrVarMove
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaStrCmp
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaNew2
'N  * ref: __vbaHresultCheckObj
'N  * ref: "System User: "
'N  * ref: __vbaStrCat
'N  * ref: vbTab
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrCat
'N  * ref: vbCrLf
'N  * ref: __vbaStrCat
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeObjList
'N  * ref: "Host Name"
'N  * ref: "host_name()"
'N  * ref: Subr_691
'N  * ref: __vbaStrVarMove
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaStrCmp
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaNew2
'N  * ref: __vbaHresultCheckObj
'N  * ref: "Host Name: "
'N  * ref: __vbaStrCat
'N  * ref: vbTab
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrCat
'N  * ref: vbCrLf
'N  * ref: __vbaStrCat
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeObjList
'N  * ref: "Server Name"
'N  * ref: "@@SERVERNAME"
'N  * ref: Subr_691
'N  * ref: __vbaStrVarMove
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaStrCmp
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaNew2
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaStrCat
'N  * ref: "Server Name: "
'N  * ref: vbTab
'N  * ref: vbCrLf
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeObjList
'N  * ref: Subr_693
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeStr
'End Sub
 
'Sub Subr_695()
'N  * ref: __vbaExceptHandler
'N  * ref: __vbaChkstk
'N  * ref: __vbaOnError
'N  * ref: __vbaVarMove
'N  * ref: ".."
'N  * ref: __vbaStrCat
'N  * ref: __vbaVarDup
'N  * ref: __vbaStrCmp
'N  * ref: IIf(
'N  * ref: ".."
'N  * ref: __vbaStrCat
'N  * ref: __vbaVarDup
'N  * ref: __vbaStrCmp
'N  * ref: IIf(
'N  * ref: "U"
'N  * ref: __vbaStrCopy
'N  * ref: Subr_688
'N  * ref: "Table Name"
'N  * ref: __vbaVarDup
'N  * ref: "select TOP 1 name from "
'N  * ref: "sysobjects where id=(select TOP 1 id from (select TOP "
'N  * ref: " id from "
'N  * ref: "sysobjects where xtype="
'N  * ref: " order BY id ASC) sq order BY id DESC)"
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: Subr_691
'N  * ref: __vbaStrVarMove
'N  * ref: __vbaStrMove
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaStrCmp
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaLateIdCallLd
'N  * ref: __vbaCastObjVar
'N  * ref: __vbaObjSet
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaCastObj
'N  * ref: __vbaObjSet
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaLateIdCallLd
'N  * ref: __vbaCastObjVar
'N  * ref: __vbaObjSet
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaObjSet
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVar
'N  * ref: __vbaHresultCheckObj
'N  * ref: "."
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrMove
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrMove
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaVarAdd
'N  * ref: __vbaVarMove
'N  * ref: __vbaStrCmp
'N  * ref: ".."
'N  * ref: __vbaStrCat
'N  * ref: __vbaVarDup
'N  * ref: __vbaStrCmp
'N  * ref: IIf(
'N  * ref: ".."
'N  * ref: __vbaStrCat
'N  * ref: __vbaVarDup
'N  * ref: __vbaStrCmp
'N  * ref: IIf(
'N  * ref: "U"
'N  * ref: __vbaStrCopy
'N  * ref: Subr_688
'N  * ref: "Table Name"
'N  * ref: __vbaVarDup
'N  * ref: "select TOP 1 name from "
'N  * ref: "sysobjects where id=(select TOP 1 id from (select TOP "
'N  * ref: " id from "
'N  * ref: "sysobjects where xtype="
'N  * ref: " order BY id ASC) sq order BY id DESC)"
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: Subr_691
'N  * ref: __vbaStrVarMove
'N  * ref: __vbaStrMove
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaStrCmp
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaLateIdCallLd
'N  * ref: __vbaCastObjVar
'N  * ref: __vbaObjSet
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaCastObj
'N  * ref: __vbaObjSet
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaLateIdCallLd
'N  * ref: __vbaCastObjVar
'N  * ref: __vbaObjSet
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaObjSet
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVar
'N  * ref: __vbaHresultCheckObj
'N  * ref: "."
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrMove
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrMove
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaVarAdd
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeObj
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStr
'End Sub
 
'Sub Subr_696()
'N  * ref: __vbaExceptHandler
'N  * ref: ".."
'N  * ref: __vbaStrCat
'N  * ref: __vbaVarDup
'N  * ref: __vbaStrCmp
'N  * ref: IIf(
'N  * ref: ".."
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrCmp
'N  * ref: IIf(
'N  * ref: Subr_688
'N  * ref: "Column Name"
'N  * ref: "select top 1 name from "
'N  * ref: "syscolumns where id=(select id from "
'N  * ref: "sysobjects where name="
'N  * ref: ")"
'N  * ref: __vbaVarCat
'N  * ref: Subr_691
'N  * ref: __vbaStrVarMove
'N  * ref: __vbaStrMove
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaStrCmp
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaLateIdCallLd
'N  * ref: __vbaCastObjVar
'N  * ref: __vbaObjSet
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaCastObj
'N  * ref: __vbaObjSet
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaLateIdCallLd
'N  * ref: __vbaCastObjVar
'N  * ref: __vbaObjSet
'N  * ref: "."
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrMove
'N  * ref: __vbaStrCat
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaObjSet
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarMove
'N  * ref: __vbaStrCmp
'N  * ref: ".."
'N  * ref: __vbaStrCat
'N  * ref: __vbaVarDup
'N  * ref: __vbaStrCmp
'N  * ref: IIf(
'N  * ref: ".."
'N  * ref: __vbaStrCat
'N  * ref: __vbaVarDup
'N  * ref: __vbaStrCmp
'N  * ref: IIf(
'N  * ref: Subr_688
'N  * ref: ".."
'N  * ref: __vbaStrCat
'N  * ref: __vbaVarDup
'N  * ref: __vbaStrCmp
'N  * ref: IIf(
'N  * ref: ".."
'N  * ref: __vbaStrCat
'N  * ref: __vbaVarDup
'N  * ref: __vbaStrCmp
'N  * ref: IIf(
'N  * ref: Subr_688
'N  * ref: "Column Name"
'N  * ref: __vbaVarDup
'N  * ref: "sysobjects where name="
'N  * ref: "select TOP 1 name from "
'N  * ref: "syscolumns where id=(select id from "
'N  * ref: ")  and name not in (select top "
'N  * ref: " name from "
'N  * ref: "syscolumns where id=(select top 1 id from "
'N  * ref: "))"
'N  * ref: Subr_691
'N  * ref: __vbaStrVarMove
'N  * ref: __vbaStrMove
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaStrCmp
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaLateIdCallLd
'N  * ref: __vbaCastObjVar
'N  * ref: __vbaObjSet
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaCastObj
'N  * ref: __vbaObjSet
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaLateIdCallLd
'N  * ref: __vbaCastObjVar
'N  * ref: __vbaObjSet
'N  * ref: "."
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrMove
'N  * ref: __vbaStrCat
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaObjSet
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarAdd
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeObj
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStr
'End Sub
 
'Sub Subr_697()
'N  * ref: __vbaExceptHandler
'N  * ref: __vbaStrCat
'N  * ref: ".."
'N  * ref: __vbaVarDup
'N  * ref: __vbaStrCmp
'N  * ref: IIf(
'N  * ref: " where "
'N  * ref: __vbaStrCmp
'N  * ref: IIf(
'N  * ref: "Row Count"
'N  * ref: "select TOP 1 count("
'N  * ref: __vbaStrMove
'N  * ref: ") from "
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: Subr_691
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeVarList
'N  * ref: IsNumeric(
'N  * ref: __vbaVarCopy
'N  * ref: __vbaStrVarVal
'N  * ref: Val(
'N  * ref: __vbaFpI4
'N  * ref: __vbaFreeStr
'N  * ref: __vbaVarTstNe
'N  * ref: __vbaStrVarVal
'N  * ref: Val(
'N  * ref: __vbaFpI4
'N  * ref: __vbaFreeStr
'N  * ref: __vbaVarDup
'N  * ref: " where "
'N  * ref: __vbaStrCmp
'N  * ref: IIf(
'N  * ref: "Count("
'N  * ref: ") of "
'N  * ref: "."
'N  * ref: __vbaVarCat
'N  * ref: " is "
'N  * ref: Subr_143
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarDup
'N  * ref: " where "
'N  * ref: __vbaStrCmp
'N  * ref: IIf(
'N  * ref: "Can not get Count("
'N  * ref: ") of "
'N  * ref: "."
'N  * ref: __vbaVarCat
'N  * ref: Subr_143
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVar
'End Sub
 
'Sub Subr_698()
'N  * ref: __vbaExceptHandler
'N  * ref: __vbaStrCat
'N  * ref: ".."
'N  * ref: __vbaVarDup
'N  * ref: __vbaStrCmp
'N  * ref: IIf(
'N  * ref: __vbaVarDup
'N  * ref: " where "
'N  * ref: __vbaStrCmp
'N  * ref: IIf(
'N  * ref: __vbaVarDup
'N  * ref: "Column Data"
'N  * ref: __vbaVarDup
'N  * ref: "select TOP 1 "
'N  * ref: __vbaStrMove
'N  * ref: " from (select TOP "
'N  * ref: __vbaStrMove
'N  * ref: __vbaStrI4
'N  * ref: __vbaStrMove
'N  * ref: __vbaStrMove
'N  * ref: " * from "
'N  * ref: __vbaVarCat
'N  * ref: " order by "
'N  * ref: " asc) sq order by "
'N  * ref: " desc"
'N  * ref: Subr_691
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarTstNe
'N  * ref: Subr_188
'N  * ref: "Data Found: "
'N  * ref: __vbaStrMove
'N  * ref: "="
'N  * ref: Subr_143
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarCopy
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVar
'End Sub
 
'Sub Subr_699()
'N  * ref: __vbaExceptHandler
'N  * ref: __vbaStrCopy
'N  * ref: Subr_700
'N  * ref: __vbaStrMove
'N  * ref: __vbaStrMove
'N  * ref: Trim(
'N  * ref: Left(
'N  * ref: LCase(
'N  * ref: "select"
'N  * ref: __vbaVarTstEq
'N  * ref: __vbaFreeVarList
'N  * ref: "Please register to activate"
'N  * ref: __vbaVarCopy
'N  * ref: "Please register to activate!"
'N  * ref: __vbaVarDup
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaNew2
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaStrBool
'N  * ref: __vbaStrComp
'N  * ref: Left(
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaVarDup
'N  * ref: "Query Result"
'N  * ref: Subr_691
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarDup
'N  * ref: IIf(
'N  * ref: __vbaStrCopy
'N  * ref: __vbaVarCat
'N  * ref: ";"
'N  * ref: "--"
'N  * ref: Subr_151
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaInStr
'N  * ref: "Query was done"
'N  * ref: __vbaVarCopy
'N  * ref: "Query failed! (maybe its done?! check it yourself)"
'N  * ref: __vbaVarCopy
'N  * ref: Subr_143
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeVar
'N  * ref: __vbaErrorOverflow
'End Sub
 
'Sub Subr_700()
'N  * ref: __vbaExceptHandler
'N  * ref: __vbaVarMove
'N  * ref: __vbaStrCopy
'N  * ref: Asc(
'N  * ref: """"
'N  * ref: "'"
'N  * ref: "'"
'N  * ref: """"
'N  * ref: __vbaVarForInit
'N  * ref: __vbaI4Var
'N  * ref: Chr(
'N  * ref: __vbaInStrVar
'N  * ref: __vbaVarTstGt
'N  * ref: __vbaFreeVarList
'N  * ref: Chr(
'N  * ref: __vbaInStrVar
'N  * ref: __vbaFreeVar
'N  * ref: Chr(
'N  * ref: __vbaVarAdd
'N  * ref: __vbaInStrVar
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarTstEq
'N  * ref: __vbaVarSub
'N  * ref: __vbaVarAdd
'N  * ref: Mid(
'N  * ref: __vbaFreeVar
'N  * ref: __vbaLenVar
'N  * ref: __vbaVarSub
'N  * ref: Mid(
'N  * ref: __vbaStrVarMove
'N  * ref: __vbaStrMove
'N  * ref: Subr_688
'N  * ref: __vbaStrVarVal
'N  * ref: __vbaStrVarVal
'N  * ref: Replace(
'N  * ref: __vbaStrMove
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarAdd
'N  * ref: __vbaVarForNext
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVar
'N  * ref: __vbaErrorOverflow
'End Sub
 
'Sub Subr_701()
'N  * ref: __vbaExceptHandler
'N  * ref: __vbaVarDup
'N  * ref: __vbaVarVargNofree
'N  * ref: __vbaVarAdd
'N  * ref: __vbaVargVarMove
'N  * ref: __vbaVarSub
'N  * ref: __vbaVarTstGt
'N  * ref: __vbaVarDiv
'N  * ref: __vbaVarInt
'N  * ref: __vbaVarAdd
'N  * ref: __vbaVarMove
'N  * ref: __vbaI4Var
'N  * ref: Chr(
'N  * ref: ": "
'N  * ref: __vbaVarCat
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarDup
'N  * ref: " "
'N  * ref: __vbaVarDup
'N  * ref: IIf(
'N  * ref: "asc(mid"
'N  * ref: "(("
'N  * ref: "),"
'N  * ref: ",1))<"
'N  * ref: __vbaStrVarVal
'N  * ref: "%True_Expression%"
'N  * ref: Replace(
'N  * ref: __vbaStrMove
'N  * ref: __vbaStrCopy
'N  * ref: Subr_151
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaInStr
'N  * ref: __vbaVarCopy
'N  * ref: Subr_701
'N  * ref: __vbaVarMove
'N  * ref: __vbaVarTstLe
'N  * ref: __vbaVarTstEq
'N  * ref: __vbaVarMove
'N  * ref: Subr_701
'N  * ref: __vbaFreeVar
'N  * ref: __vbaVarMove
'N  * ref: "?"
'N  * ref: Asc(
'N  * ref: __vbaVarMove
'N  * ref: __vbaI4Var
'N  * ref: Chr(
'N  * ref: ": "
'N  * ref: __vbaVarCat
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarDup
'N  * ref: " "
'N  * ref: __vbaVarDup
'N  * ref: IIf(
'N  * ref: "asc(mid"
'N  * ref: "(("
'N  * ref: "),"
'N  * ref: ",1))="
'N  * ref: __vbaStrVarVal
'N  * ref: "%True_Expression%"
'N  * ref: Replace(
'N  * ref: __vbaStrMove
'N  * ref: __vbaStrCopy
'N  * ref: Subr_151
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaInStr
'N  * ref: __vbaVarCopy
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVar
'End Sub
 
