Attribute VB_Name = "Registry"
' This code module rebuilt by VBRezQ v3.3a.  2-Feb-2012 / 19:56:47
Option Explicit 
 
'Sub Subr_754()
'N  * ref: __vbaExceptHandler
'N  * ref: __vbaI4Var
'N  * ref: __vbaStrToAnsi
'N  * API ref: RegCreateKeyA
'N  * ref: __vbaSetSystemError
'N  * ref: __vbaStrToUnicode
'N  * ref: __vbaVarCopy
'N  * ref: __vbaFreeStr
'N  * ref: __vbaLenBstr
'N  * API ref: RegSetValueExA
'N  * ref: __vbaStrToUnicode
'N  * ref: __vbaFreeStrList
'N  * API ref: RegCloseKey
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVar
'End Sub
 
'Sub Subr_755()
'N  * ref: __vbaExceptHandler
'N  * ref: IsEmpty(
'N  * ref: __vbaStrCopy
'N  * ref: __vbaStrToAnsi
'N  * API ref: RegOpenKeyA
'N  * ref: __vbaSetSystemError
'N  * ref: __vbaStrToUnicode
'N  * ref: __vbaFreeStr
'N  * API ref: RegQueryValueExA
'N  * ref: __vbaSetSystemError
'N  * ref: __vbaFreeStr
'N  * ref: __vbaVarTstEq
'N  * ref: " "
'N  * ref: __vbaVarDup
'N  * ref: String(
'N  * ref: __vbaStrVarMove
'N  * ref: __vbaStrMove
'N  * ref: __vbaFreeVarList
'N  * API ref: RegQueryValueExA
'N  * ref: __vbaSetSystemError
'N  * ref: __vbaFreeStrList
'N  * ref: Chr$(
'N  * ref: __vbaStrMove
'N  * ref: __vbaInStr
'N  * ref: __vbaI2I4
'N  * ref: __vbaFreeStr
'N  * ref: Left$(
'N  * ref: __vbaStrCopy
'N  * API ref: RegCloseKey
'N  * ref: __vbaSetSystemError
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStr
'N  * ref: __vbaErrorOverflow
'End Sub
 
